remote_theme: jekyll/minima
title: Mi Blog
description: Un blog minimalista y moderno
baseurl: ""
url: "https://username.github.io"

github:
  branch: new_blog

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
