remote_theme: jekyll/minima
title: The Log - Mario Romero
description: Soluciones a problemas de programación y tecnología
baseurl: ""
url: "https://maaroarg.github.io"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
